### ISSUE TITLE
error about metadata.json

### ISSUE THREAD

**Issue by caseyu1989** [zqhZY/_rasa_chatbot#16]
Hi,

Can you tell me how to fix this issue? I can not find metadata.json in project.
Thanks.

C:\Project\RASA_DEMO\_rasa_chatbot-master>python bot.py train-nlu
Traceback (most recent call last):
  File "C:\python\python3_6_5_64\lib\site-packages\rasa_nlu\model.py", line 56, in load
    with io.open(metadata_file, encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'models/ivr/demo\\metadata.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bot.py", line 120, in <module>
    interpreter=RasaNLUInterpreter("models/ivr/demo"),
  File "C:\python\python3_6_5_64\lib\site-packages\rasa_core\interpreter.py", line 219, in __init__
    self._load_interpreter()
  File "C:\python\python3_6_5_64\lib\site-packages\rasa_core\interpreter.py", line 238, in _load_interpreter
    os.environ))
  File "C:\python\python3_6_5_64\lib\site-packages\rasa_nlu\model.py", line 228, in load
    model_metadata = Metadata.load(model_dir)
  File "C:\python\python3_6_5_64\lib\site-packages\rasa_nlu\model.py", line 62, in load
    "from '{}'. {}".format(abspath, e))
rasa_nlu.model.InvalidProjectError: Failed to load model metadata from 'C:\Project\RASA_DEMO\_rasa_chatbot-master\models\ivr\demo\metadata.json'. [Errno 2] No such file or directory: 'models/ivr/demo\\metadata.json'

**Comment by fangnster** [comment]
I have met same problem, and I think the code is not complete , is it ?

**Comment by zqhZY** [comment]
Thanks for issue! yes, this project has no pre-trained model and train data. I will upload it later.

**Comment by leoboycorpse** [comment]
Hey guys,
You can try 

python -m rasa_nlu.train --config  mobile_nlu_model_config.json --data data/mobile_nlu_data.json  --path models

then you will get models project , but you have to change the project name to "ivr" and "demo"

try it

**Comment by zqhZY** [comment]
May be you can add project name and model name config in mobile_nlu_model_config.json  for the specific project name. @leoboycorpse . 
The interface of rasa has been changed a lot, and I will update this project latter.
