### ISSUE TITLE
train-dialogue报错

### ISSUE THREAD

**Issue by JiahangOK** [zqhZY/_rasa_chatbot#20]
请问什么时候可以更新呢？我是完全按照 README 去做的，目前这个开源代码运行到python bot.py train-dialogue就运行不了了，报错：  
‘’‘
Traceback (most recent call last):
  File "/home/jiahang/env/lib/python3.6/site-packages/rasa_nlu/model.py", line 74, in load
    data = utils.read_json_file(metadata_file)
  File "/home/jiahang/env/lib/python3.6/site-packages/rasa_nlu/utils/__init__.py", line 208, in read_json_file
    content = read_file(filename)
  File "/home/jiahang/env/lib/python3.6/site-packages/rasa_nlu/utils/__init__.py", line 202, in read_file
    with io.open(filename, encoding=encoding) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'models/ivr/demo/metadata.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bot.py", line 120, in <module>
    interpreter=RasaNLUInterpreter("models/ivr/demo"),
  File "/home/jiahang/env/lib/python3.6/site-packages/rasa_core/interpreter.py", line 245, in __init__
    self._load_interpreter()
  File "/home/jiahang/env/lib/python3.6/site-packages/rasa_core/interpreter.py", line 261, in _load_interpreter
    self.interpreter = Interpreter.load(self.model_directory)
  File "/home/jiahang/env/lib/python3.6/site-packages/rasa_nlu/model.py", line 288, in load
    model_metadata = Metadata.load(model_dir)
  File "/home/jiahang/env/lib/python3.6/site-packages/rasa_nlu/model.py", line 79, in load
    "from '{}'. {}".format(abspath, e))
rasa_nlu.model.InvalidProjectError: Failed to load model metadata from '/home/jiahang/_rasa_chatbot/models/ivr/demo/metadata.json'. [Errno 2] No such file or directory: 'models/ivr/demo/metadata.json'
‘’’
之前已经用python -m rasa_nlu.train --config  mobile_nlu_model_config.json --data data/mobile_nlu_data.json  --path models训练好数据了，求解答。

**Comment by leozhang888** [comment]
I have similar issue: "can not access action 'action_search consume', as that name is not a registered action for this domain."
So I did two things:

1. I implement external custom action named action_search_consume by NodeJs, and add endpoints to run function in bot.py and it works:
2. Remove line 'from rasa_core.channels.console import ConsoleInputChannel' as it is not valid in Rasa_core 11.0+. 
Use serv_application function to start bot.

Finally the run function looks like below:
def run(serve_forever=True):
    # agent = Agent.load("projects/dialogue",
    #                    interpreter=RasaNLUInterpreter("projects/ivr_nlu/demo"))
    action_endpoint = EndpointConfig(url="http://localhost:8601/nlp/mobile_bot")
    agent = Agent.load("projects/dialogue",
                       interpreter=RasaNLUInterpreter("projects/ivr_nlu/demo"),
                       action_endpoint=action_endpoint)
    if serve_forever:
        serve_application(agent, channel='cmdline')
    return agent
