### ISSUE TITLE
请问作者的python版本是多少？我python3.6的发请求后服务器一大堆报错：

### ISSUE THREAD

**Issue by Jason-Song** [zqhZY/_rasa_chatbot#26]

**Comment by Jason-Song** [comment]
2019-01-15 09:44:31+0800 [-] Unhandled Error
        Traceback (most recent call last):
          File "C:\python36\lib\site-packages\twisted\web\server.py", line 259, in render
            body = resrc.render(self)
          File "C:\python36\lib\site-packages\klein\resource.py", line 210, in render
            d = defer.maybeDeferred(_execute)
          File "C:\python36\lib\site-packages\twisted\internet\defer.py", line 151, in maybeDeferred
            result = f(*args, **kw)
          File "C:\python36\lib\site-packages\klein\resource.py", line 204, in _execute
            **kwargs)
        --- <exception caught here> ---
          File "C:\python36\lib\site-packages\twisted\internet\defer.py", line 151, in maybeDeferred
            result = f(*args, **kw)
          File "C:\python36\lib\site-packages\klein\app.py", line 128, in execute_endpoint
            return endpoint_f(self._instance, *args, **kwargs)
          File "C:\python36\lib\site-packages\klein\app.py", line 227, in _f
            return _call(instance, f, request, *a, **kw)
          File "C:\python36\lib\site-packages\klein\app.py", line 50, in _call
            result = f(*args, **kwargs)
          File "httpserver.py", line 47, in save_item
            pred = self.interpreter.parse(data["q"])
          File "C:\python36\lib\site-packages\rasa_nlu\model.py", line 340, in parse
            component.process(message, **self.context)
          File "C:\python36\lib\site-packages\rasa_nlu\classifiers\sklearn_intent_classifier.py", line 172, in process
            intents = self.transform_labels_num2str(intent_ids)
          File "C:\python36\lib\site-packages\rasa_nlu\classifiers\sklearn_intent_classifier.py", line 108, in transform_labels_num2str
            return self.le.inverse_transform(y)
          File "C:\python36\lib\site-packages\sklearn\preprocessing\label.py", line 273, in inverse_transform
            y = column_or_1d(y, warn=True)
          File "C:\python36\lib\site-packages\sklearn\utils\validation.py", line 797, in column_or_1d
            raise ValueError("bad input shape {0}".format(shape))
        builtins.ValueError: bad input shape (1, 13)

**Comment by zqhZY** [comment]
可能是rasa 版本更新的问题，安装rasa_core==0.9.0（会自动安装rasa nlu）试试

**Comment by babyeleven** [comment]
您好，不支持rasa_core==0.12.1嘛？

**Comment by GaoQ1** [comment]
> 您好，不支持rasa_core==0.12.1嘛？

[rasa_chatbot_cn](https://github.com/GaoQ1/rasa_chatbot_cn)支持的噢

**Comment by xxllp** [comment]
@Jason-Song 你的问题解决了吗

**Comment by zhangrenjie666666** [comment]
@ Jason-Song 可以说下你的问题怎么解决的吗

**Comment by Chenny0808** [comment]
@Jason-Song 我也遇到了此问题，可以说下你的问题怎么解决的吗

**Comment by Chenny0808** [comment]
@xxllp scikit-learn 要为0.19.2，我修改sklearn版本后就好了
